apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server
  namespace: minecraft-server
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
