---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-service
spec:
  type: NodePort
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: minecraft-server